<?php
include"../template/header.php";
include"../template/preloader.php";
include"../template/topbar.php";
include"../pages/aboutus.php";
include"../pages/missionandvission.php";
include"../pages/team.php";
include"../pages/aboutsoftware.php";
include"../template/footer.php";
?>